# Generated by Django 5.0.3 on 2024-05-30 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_billtable_carttable_producttable_signuptable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caketable',
            fields=[
                ('producttable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.producttable')),
            ],
            bases=('app.producttable',),
        ),
        migrations.CreateModel(
            name='Chocolatetable',
            fields=[
                ('producttable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.producttable')),
            ],
            bases=('app.producttable',),
        ),
        migrations.RenameField(
            model_name='producttable',
            old_name='unit_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='producttable',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='billtable',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
