# Generated by Django 5.0.3 on 2024-06-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_price_billtable_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttable',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='billtable',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='billtable',
            name='product',
        ),
        migrations.RemoveField(
            model_name='billtable',
            name='user',
        ),
        migrations.RemoveField(
            model_name='carttable',
            name='product',
        ),
        migrations.RemoveField(
            model_name='carttable',
            name='user',
        ),
        migrations.RemoveField(
            model_name='producttable',
            name='user',
        ),
        migrations.AddField(
            model_name='billtable',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billtable',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billtable',
            name='product_name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='billtable',
            name='user_id',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='carttable',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carttable',
            name='product_name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='carttable',
            name='user_id',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='billtable',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='carttable',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='signuptable',
            name='first_name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='signuptable',
            name='last_name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='signuptable',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signuptable',
            name='password',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='signuptable',
            name='place',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
