# Generated by Django 5.0.3 on 2024-06-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_price_producttable_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtable',
            name='first_name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='billtable',
            name='last_name',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
