# Generated by Django 5.0.3 on 2024-06-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_billtable_first_name_billtable_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtable',
            name='email',
            field=models.EmailField(default='default@default.com', max_length=254),
        ),
    ]
